/**
 * One-time data seed script.
 *
 * Populates the Amplify/DynamoDB database with the 25 existing grants
 * from src/data.ts.
 *
 * Prerequisites:
 *   - A healthy Amplify sandbox (npx ampx sandbox) or deployed environment.
 *   - amplify_outputs.json present at the project root.
 *
 * Usage:
 *   npx ts-node scripts/seed.ts
 */

import { Amplify } from 'aws-amplify';
// amplify_outputs.json is generated by `npx ampx sandbox` and is gitignored.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const outputs = require('../amplify_outputs.json');

import { grants } from '../src/data';
import { client } from '../src/amplifyClient';

Amplify.configure(outputs);

async function seed() {
  console.log(`Seeding ${grants.length} grants…\n`);

  let successCount = 0;
  let errorCount = 0;

  for (const grant of grants) {
    // Destructure out id, createdAt, and updatedAt — Amplify generates these.
    const { id: _id, createdAt: _createdAt, updatedAt: _updatedAt, ...grantData } = grant;

    try {
      const { data, errors } = await client.models.Grant.create(grantData);

      if (errors && errors.length > 0) {
        console.error(`✗ Failed to create "${grant.name}":`, errors);
        errorCount++;
      } else {
        console.log(`✓ Created "${data?.name}" (id: ${data?.id})`);
        successCount++;
      }
    } catch (err) {
      console.error(`✗ Exception creating "${grant.name}":`, err);
      errorCount++;
    }
  }

  console.log(`\nDone. ${successCount} succeeded, ${errorCount} failed.`);
}

seed().catch((err) => {
  console.error('Seed script failed:', err);
  process.exit(1);
});
