export interface Grant {
  id: string;          // was: number — Amplify generates UUID strings
  name: string;
  contactEmail: string;
  nextDeadline: string;
  eligibilityRequirements: string;
  bloomPowerFitNotes: string;
  geographicEligibility: string;
  typicalAward: string;
  applicationStatus: string;
  url: string;
  createdAt?: string;
  updatedAt?: string;
}

export const grants: Grant[] = [
  {
    id: '1',
    name: 'Bank of America Charitable Foundation',
    contactEmail: 'foundation@bofa.com',
    nextDeadline: 'TBD — 2026 windows have passed',
    eligibilityRequirements: '501(c)(3); must serve an eligible Bank of America market and meet applicable funding-priority requirements.',
    bloomPowerFitNotes: "Excellent fit for Bloom Power's financial literacy, entrepreneurship, workforce readiness, leadership, and economic-mobility programming.",
    geographicEligibility: 'National (eligible BofA markets)',
    typicalAward: '$25k–$200k',
    applicationStatus: 'Researching',
    url: 'https://about.bankofamerica.com/en/making-an-impact/charitable-foundation-grant-faq',
  },
  {
    id: '2',
    name: 'Florida Blue Foundation',
    contactEmail: 'floridabluefoundation@floridablue.com',
    nextDeadline: 'TBD',
    eligibilityRequirements: "Florida nonprofit aligned with the Foundation's current strategic priorities; exact eligibility varies by grant program.",
    bloomPowerFitNotes: 'Strong fit for youth development, social-emotional learning, confidence, leadership, wellness, and family/community engagement.',
    geographicEligibility: 'Florida',
    typicalAward: '$25k–$200k',
    applicationStatus: 'Researching',
    url: 'https://www.floridablue.com/foundation/community-investments',
  },
  {
    id: '3',
    name: 'Publix Charities',
    contactEmail: 'charitable.donationshelp@publix.com',
    nextDeadline: 'Rolling / TBD',
    eligibilityRequirements: "Eligible nonprofit, school, or government organization serving Publix's operating footprint and fitting applicable charitable priorities.",
    bloomPowerFitNotes: 'Excellent Florida fit for youth empowerment, education, mentoring, leadership, and community engagement.',
    geographicEligibility: 'Southeast U.S.',
    typicalAward: '$5k–$100k',
    applicationStatus: 'Researching',
    url: 'https://corporate.publix.com/community/giving',
  },
  {
    id: '4',
    name: 'Walmart Spark Good Local Grants',
    contactEmail: 'TBD',
    nextDeadline: 'TBD — verify current cycle',
    eligibilityRequirements: "Eligible organizations must maintain required Spark Good/Deed verification and meet Walmart's nonprofit eligibility rules.",
    bloomPowerFitNotes: 'Strong fit for local service projects, environmental activities, financial-literacy events, youth leadership, and volunteerism.',
    geographicEligibility: 'National',
    typicalAward: '$250–$5,000',
    applicationStatus: 'Researching',
    url: 'https://walmart.org/sparkgood',
  },
  {
    id: '5',
    name: 'PNC Foundation / PNC Grow Up Great',
    contactEmail: 'pnc.growupgreat@pnc.com',
    nextDeadline: 'Varies by program/region; TBD',
    eligibilityRequirements: 'Eligibility and application requirements vary by PNC program and geography; eligible nonprofits must meet the applicable program criteria.',
    bloomPowerFitNotes: 'Good fit when Bloom emphasizes financial education, economic opportunity, education, or community development.',
    geographicEligibility: 'National (PNC footprint)',
    typicalAward: '$10k–$100k',
    applicationStatus: 'Researching',
    url: 'https://www.pnc.com/en/about-pnc/corporate-responsibility/philanthropy.html',
  },
  {
    id: '6',
    name: 'Wells Fargo Foundation',
    contactEmail: 'grantadministration@wellsfargo.com',
    nextDeadline: 'TBD',
    eligibilityRequirements: 'Eligible nonprofit organizations and other qualifying entities; many corporate opportunities are relationship- or invitation-based.',
    bloomPowerFitNotes: 'Strong fit for financial empowerment, entrepreneurship, workforce readiness, and economic-opportunity programming.',
    geographicEligibility: 'National',
    typicalAward: '$25k–$250k',
    applicationStatus: 'Researching',
    url: 'https://www.wellsfargo.com/about/corporate-responsibility/community-giving/',
  },
  {
    id: '7',
    name: 'State Farm Good Neighbor Citizenship Company Grants',
    contactEmail: 'TBD',
    nextDeadline: 'TBD — invitation process',
    eligibilityRequirements: '501(c)(3) charitable nonprofits and other listed eligible entities; current opportunities are generally invitation-based.',
    bloomPowerFitNotes: 'Strong fit for financial literacy, education, leadership, mentoring, community development, and STEM.',
    geographicEligibility: 'National',
    typicalAward: '$25k–$100k',
    applicationStatus: 'Researching',
    url: 'https://www.statefarm.com/about-us/community-grants',
  },
  {
    id: '8',
    name: 'Youth Service America – We Serve to Remember 9/11 Day of Service Grants',
    contactEmail: 'sganske@ysa.org',
    nextDeadline: 'TBD — 2026 deadline passed',
    eligibilityRequirements: 'U.S.-based organizations, schools, and youth changemakers; individual cycle requirements include youth-led service and minimum participation requirements.',
    bloomPowerFitNotes: "Very strong fit for Bloom's teen service, leadership, teamwork, volunteerism, civic responsibility, and community engagement.",
    geographicEligibility: 'National',
    typicalAward: '$250–$1,000',
    applicationStatus: 'Researching',
    url: 'https://ysa.org/grants/',
  },
  {
    id: '9',
    name: 'The Allstate Foundation – Good Starts Young / community giving',
    contactEmail: 'TBD',
    nextDeadline: 'TBD',
    eligibilityRequirements: 'Eligibility and application access vary by current program; confirm the current application pathway and nonprofit requirements.',
    bloomPowerFitNotes: 'Strong fit for youth empowerment, social-emotional skills, confidence, leadership, service, and community impact.',
    geographicEligibility: 'National',
    typicalAward: 'Varies',
    applicationStatus: 'Researching',
    url: 'https://www.nassp.org/programs/student-programs/national-student-council/',
  },
  {
    id: '10',
    name: 'National Environmental Education Foundation (NEEF) – Grant Programs',
    contactEmail: 'grants@neefusa.org',
    nextDeadline: 'TBD',
    eligibilityRequirements: 'Eligibility varies by individual NEEF grant; opportunities may require eligible nonprofit status and/or partnerships.',
    bloomPowerFitNotes: 'Strong fit for environmental education, youth-led conservation, outdoor learning, sustainability, and service-learning.',
    geographicEligibility: 'National',
    typicalAward: '$5k–$50k',
    applicationStatus: 'Researching',
    url: 'https://www.neefusa.org/grants',
  },
  {
    id: '11',
    name: 'US Department of Health and Human Services (HHS) – Grants.gov opportunities',
    contactEmail: 'TBD',
    nextDeadline: 'TBD',
    eligibilityRequirements: 'Eligibility is opportunity-specific; federal applicants must meet the applicable NOFO, registration, and compliance requirements.',
    bloomPowerFitNotes: 'Potential fit when a NOFO supports youth development, workforce readiness, social-emotional supports, education, or community opportunity.',
    geographicEligibility: 'National',
    typicalAward: '$100k+',
    applicationStatus: 'Researching',
    url: 'https://www.grants.gov',
  },
  {
    id: '12',
    name: 'American Legion Child Welfare Foundation',
    contactEmail: 'TBD',
    nextDeadline: 'TBD',
    eligibilityRequirements: "Grant eligibility and priorities are set by the Foundation's current cycle and generally focus on organizations serving children and youth.",
    bloomPowerFitNotes: 'Good fit for youth development, mentoring, character development, leadership, and life-skills programming.',
    geographicEligibility: 'National',
    typicalAward: '$5k–$50k',
    applicationStatus: 'Researching',
    url: 'https://cwf-inc.org',
  },
  {
    id: '13',
    name: 'Youth as Resources',
    contactEmail: 'jreeder@youthasresources.org',
    nextDeadline: 'TBD',
    eligibilityRequirements: 'Eligibility varies by local Youth as Resources program/site; generally supports youth-led community service and civic engagement projects.',
    bloomPowerFitNotes: "Very strong fit for Bloom's teen service, civic responsibility, volunteerism, leadership, teamwork, and community engagement.",
    geographicEligibility: 'Select markets',
    typicalAward: '$500–$10k',
    applicationStatus: 'Researching',
    url: 'https://www.youthasresources.org',
  },
  {
    id: '14',
    name: 'Project Learning Tree / Environmental Education Grants',
    contactEmail: 'TBD',
    nextDeadline: 'TBD',
    eligibilityRequirements: 'Eligibility varies by current PLT grant; opportunities generally support environmental education, youth engagement, outdoor learning, and educator capacity.',
    bloomPowerFitNotes: 'Strong fit for environmental education and stewardship, especially youth-led conservation and sustainability projects.',
    geographicEligibility: 'National',
    typicalAward: 'Varies',
    applicationStatus: 'Researching',
    url: 'https://www.plt.org',
  },
  {
    id: '15',
    name: 'Jim Moran Foundation',
    contactEmail: 'TBD',
    nextDeadline: 'TBD',
    eligibilityRequirements: "Florida nonprofits must meet the Foundation's current program-area and geographic requirements; funding priorities vary by initiative.",
    bloomPowerFitNotes: 'Strong Florida prospect for youth development, education, confidence, life skills, and measurable community impact.',
    geographicEligibility: 'Florida',
    typicalAward: '$25k+',
    applicationStatus: 'Researching',
    url: 'https://jimmoranfoundation.org/grant/guidelines',
  },
  {
    id: '16',
    name: "Children's Services Council of Broward County",
    contactEmail: 'info@cscbroward.org',
    nextDeadline: 'TBD',
    eligibilityRequirements: "Eligibility is program- and procurement-specific and may require qualifying Broward County service delivery, reporting capacity, and compliance with CSC rules.",
    bloomPowerFitNotes: "Extremely strong geographic and mission fit for Bloom's Broward youth development, mentoring, SEL, family engagement, and educational enrichment.",
    geographicEligibility: 'Broward County, FL',
    typicalAward: '$50k+',
    applicationStatus: 'Researching',
    url: 'https://www.cscbroward.org/provider/',
  },
  {
    id: '17',
    name: 'Helios Education Foundation',
    contactEmail: 'TBD',
    nextDeadline: 'TBD',
    eligibilityRequirements: 'Programs and eligibility are initiative-specific and generally focus on education, postsecondary attainment, and economic mobility in service regions.',
    bloomPowerFitNotes: 'Good fit for college/career readiness, workforce preparation, academic enrichment, financial literacy, and leadership.',
    geographicEligibility: 'Florida & Arizona',
    typicalAward: '$50k+',
    applicationStatus: 'Researching',
    url: 'https://www.helios.org/grants',
  },
  {
    id: '18',
    name: 'OYC Miami',
    contactEmail: 'TBD',
    nextDeadline: 'TBD',
    eligibilityRequirements: 'Eligibility and application requirements vary by current opportunity; confirm whether the opportunity is open to independent nonprofits and its geographic requirements.',
    bloomPowerFitNotes: 'Strong local thematic fit for youth empowerment, mentoring, leadership, service, and positive youth development.',
    geographicEligibility: 'Miami-Dade County, FL',
    typicalAward: 'Partnership-based',
    applicationStatus: 'Researching',
    url: 'https://www.oycmiami.org',
  },
  {
    id: '19',
    name: 'Community Foundation of Broward',
    contactEmail: 'grants@cfbroward.org',
    nextDeadline: 'TBD',
    eligibilityRequirements: "Eligibility varies by fund and grant cycle; eligible nonprofits generally must serve Broward County and meet the fund's charitable purpose and application requirements.",
    bloomPowerFitNotes: "Excellent geographic fit. Bloom's youth leadership, financial empowerment, environmental stewardship, entrepreneurship, and community service can align with relevant Broward funds.",
    geographicEligibility: 'Broward County, FL',
    typicalAward: '$10k+',
    applicationStatus: 'Researching',
    url: 'https://www.cfbroward.org/receive/apply-for-grants',
  },
  {
    id: '20',
    name: 'Florida Humanities',
    contactEmail: 'grants@flahum.org',
    nextDeadline: 'August 5, 2026',
    eligibilityRequirements: 'Eligibility varies by program; public humanities opportunities generally require eligible nonprofit status, humanities content, public benefit, and required application materials.',
    bloomPowerFitNotes: 'Good fit when Bloom incorporates civic engagement, cultural learning, ethics, history, communication, or community dialogue into youth programming.',
    geographicEligibility: 'Florida',
    typicalAward: '$5k–$25k',
    applicationStatus: 'Researching',
    url: 'https://floridahumanities.org/grants',
  },
  {
    id: '21',
    name: 'Truist Foundation',
    contactEmail: 'truistfoundation@truist.com',
    nextDeadline: 'TBD',
    eligibilityRequirements: 'Current funding opportunities are program-specific and may be invitation-based or announced through targeted initiatives; applicants must meet applicable nonprofit, geographic, and program requirements.',
    bloomPowerFitNotes: 'Strong fit for financial empowerment, entrepreneurship, workforce readiness, and economic mobility. Bloom can frame youth financial literacy as an early economic-mobility intervention.',
    geographicEligibility: 'National (Truist footprint)',
    typicalAward: '$5k+',
    applicationStatus: 'Researching',
    url: 'https://www.truist.com/purpose/truist-foundation/grant-application',
  },
  {
    id: '22',
    name: 'Citizens Foundation / Citizens corporate giving',
    contactEmail: 'TBD',
    nextDeadline: 'TBD',
    eligibilityRequirements: "Eligibility and access depend on the current Citizens giving program and geographic priorities; verify whether the specific opportunity is open in Bloom's service area.",
    bloomPowerFitNotes: 'Potentially strong for financial literacy, economic empowerment, education, and community development.',
    geographicEligibility: 'Citizens Bank footprint',
    typicalAward: '$10k+',
    applicationStatus: 'Researching',
    url: 'https://www.citizensbank.com/about-us/community/corporate-giving.aspx',
  },
  {
    id: '23',
    name: 'TD Charitable Foundation',
    contactEmail: 'FloridaCharitableGiving@td.com',
    nextDeadline: 'TBD',
    eligibilityRequirements: 'Eligibility and priorities vary by current grant program; applications must satisfy the applicable nonprofit, geographic, and program requirements.',
    bloomPowerFitNotes: 'Strong fit for financial literacy, economic mobility, community development, and youth opportunity when the active program permits youth-serving nonprofits.',
    geographicEligibility: 'TD Bank footprint',
    typicalAward: '$10k+',
    applicationStatus: 'Researching',
    url: 'https://www.tdbank.com/corporate-responsibility/the-ready-commitment/',
  },
  {
    id: '24',
    name: 'First Horizon Foundation',
    contactEmail: 'Foundation@FirstHorizon.com',
    nextDeadline: 'TBD',
    eligibilityRequirements: 'Eligibility and deadlines vary by current foundation program and service area; qualifying nonprofits must fit published charitable priorities.',
    bloomPowerFitNotes: 'Potential fit for education, community development, financial capability, and youth opportunity.',
    geographicEligibility: 'First Horizon footprint',
    typicalAward: '$5k+',
    applicationStatus: 'Researching',
    url: 'https://www.firsthorizonfoundation.com',
  },
  {
    id: '25',
    name: 'NBCUniversal Local Impact Grants',
    contactEmail: 'TBD',
    nextDeadline: 'TBD',
    eligibilityRequirements: 'Eligibility and geography depend on the current Local Impact Grants cycle and participating local markets; applicants must meet published nonprofit requirements.',
    bloomPowerFitNotes: 'Strong potential fit for youth empowerment, education, community engagement, entrepreneurship, and environmental initiatives with measurable local impact.',
    geographicEligibility: 'Eligible local markets',
    typicalAward: '$2,500+',
    applicationStatus: 'Researching',
    url: 'https://www.localimpactgrants.com/',
  },
];
