import { Amplify } from 'aws-amplify';
// @ts-ignore — amplify_outputs.json is generated by `npx ampx sandbox` and is gitignored
import outputs from '../amplify_outputs.json';
Amplify.configure(outputs);

import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);
